server:
  port: 8080
spring:
  mvc:
    view:
      prefix: WEB-INF/jsp/
      suffix: .jsp
    static-path-pattern: /**
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://47.100.24.231:3306/test1?characterEncoding=utf8
    #url: jdbc:mysql://localhost:3306/test1?characterEncoding=utf8
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000






mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.project.entity
#showSql
logging:
  level:
    com:
      example:
        mapper : debug
